baseURL = 'https://m7kvqbe1.dev/'
languageCode = 'en-gb'
title = 'm7kvqbe1.dev'
theme = 'PaperMod'

[params]
defaultTheme = 'light'

[params.homeInfoParams]
Title = "Hi, I'm Tom."
Content = "This is a personal blog where I (infrequently) write about technology and other topics of interest to me. I currently work at Royal Navy DNA. Before that I was a Lead Software Engineer at Simpplr, Inc."

[[params.socialIcons]]
name = "GitHub"
url = "https://github.com/m7kvqbe1"

[[params.socialIcons]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/tom-humphris-392b2251/"
